### PR TITLE
Turn on texture filtering

### PR DESCRIPTION
**Pull request by fire**
Remembering the textures were not pixelated.

### CODE REVIEW

**Comment by fire** [comment]
https://user-images.githubusercontent.com/32321/119246345-aa509280-bb35-11eb-8e60-5fe760960048.mp4

Looks closer to how I remember it.

**Comment by DataPlusProgram** [comment]
image

You can change the texture filtering like this.
You can then click "Preset" and "Set as default" to have it always use texture filtering.

There are use cases for both filtered and unfiltered. I thought unfiltered looked the cleanest so I set that as the default value.

**Comment by Calinou** [comment]
Given the low texture resolution, I feel it looks better with filtering disabled, but that's just me :slightly_smiling_face:

Also, if you use the software renderer in GoldSrc games, textures use nearest-neighbor filtering instead of linear filtering. Even Valve themselves disabled texture filtering when they brought back the CS 1.6 de_dust2 to CS:GO in mid-2019 for the game's 20th anniversary, so we might as well consider nearest-neighbor filtering "canon".

**Comment by fire** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
